CREATE TABLE PSTS
(NOMSKLAD int PRIMARY KEY,
NOMDOK int UNIQUE,
NOMDOG int,
KODDET int,
KOL int DEFAULT 0,
DATAP date CHECK (DATAP > 2004-03-01))

CREATE TABLE DOG
(NOMDOG int PRIMARY KEY,
KODDET int UNIQUE,
DTN date CHECK (DTN > 2004-01-01),
DTK date CHECK (DTK > DTN),
PLUN int,
DOGSTOIM int)

CREATE TABLE DET
(KODDET int PRIMARY KEY,
TIP int,
NAMEDET varchar,
PLANSTOIM int CHECK (PLANSTOIM > 0))